name: Build Amethyst Mod
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Pull Submodules Recursively
        run: |
          git submodule update --init --recursive

      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Build with xmake
        run: |
          xmake config -y
          xmake -y

      - name: Upload Mod
        uses: actions/upload-artifact@v4
        with:
          name: Compiled-Mod
          path: build/
