name: Build Amethyst Mod
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup xmake
        run: |
          Invoke-Expression (Invoke-WebRequest 'https://xmake.io/psget.text' -UseBasicParsing).Content

      - name: Build with xmake
        run: |
          $env:PATH += ";$env:LOCALAPPDATA\xmake"
          xmake config -a x86_64 -y
          xmake -y

      - name: Upload Mod
        uses: actions/upload-artifact@v4
        with:
          name: Compiled-Mod
          path: build/
